"""
Tests for the program_template module.

Run from the Agentic_System directory:
    python -m pytest tests/test_program_template.py -v
"""

import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

_here = Path(__file__).resolve().parent
_agentic_dir = _here.parent
_ikacore_src = _agentic_dir / "IkaCore" / "src"
for candidate in [str(_agentic_dir), str(_ikacore_src)]:
    if candidate not in sys.path:
        sys.path.insert(0, candidate)

if "IkaCore" not in sys.modules:
    import types

    ika_pkg = types.ModuleType("IkaCore")
    ika_tools_mod = types.ModuleType("IkaCore.tools")

    class _IkaTools:
        def __init__(self, name, description, parameters, execute_function, **kwargs):
            self.name = name
            self.description = description
            self.parameters = parameters
            self.execute_function = execute_function

    ika_tools_mod.IkaTools = _IkaTools
    ika_pkg.tools = ika_tools_mod
    sys.modules["IkaCore"] = ika_pkg
    sys.modules["IkaCore.tools"] = ika_tools_mod


MINIMAL_TEMPLATES_SWIFT = """\
// Autogenerated
let programTemplates: [ProgramTemplateProtocol] = [

    ProgramTemplate("Codegen100") { b in
        b.buildPrefix()
        b.build(n: 100)
    },

    ProgramTemplate("JIT1Function") { b in
        b.buildRepeatLoop(n: 100)
    },

]
"""

MINIMAL_WEIGHTS_SWIFT = """\
let programTemplateWeights: [String: Int] = [
\t"Codegen100": 2,
\t"JIT1Function": 2,
]
"""


def _make_swift_files(tmp: Path) -> tuple[Path, Path]:
    swift_dir = tmp / "Sources" / "Fuzzilli" / "CodeGen"
    swift_dir.mkdir(parents=True)
    templates_file = swift_dir / "ProgramTemplates.swift"
    weights_file = swift_dir / "ProgramTemplateWeights.swift"
    templates_file.write_text(MINIMAL_TEMPLATES_SWIFT)
    weights_file.write_text(MINIMAL_WEIGHTS_SWIFT)
    return templates_file, weights_file


class TestProgramTemplate(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        self.templates_file, self.weights_file = _make_swift_files(self.tmp)

        import uuid
        from datetime import datetime

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.session_id = f"fog_{timestamp}_{uuid.uuid4().hex[:8]}"
        self.session_dir = self.tmp / "runtime_data" / "fog_sessions" / self.session_id

        self._patches = [
            patch("tools.FoG_tools._shared.PROGRAM_TEMPLATES_FILE", self.templates_file),
            patch("tools.FoG_tools._shared.PROGRAM_WEIGHTS_FILE", self.weights_file),
            patch("tools.FoG_tools._shared.FOG_SESSION_ID", self.session_id),
            patch("tools.FoG_tools._shared.SESSION_DIR", self.session_dir),
            patch("tools.FoG_tools._shared.TEMPLATE_BACKUP_DIR", self.session_dir / "template_backups"),
            patch("tools.FoG_tools._shared.SESSION_METADATA_FILE", self.session_dir / "metadata.json"),
            patch(
                "tools.FoG_tools._shared.GENERATED_TEMPLATE_DIR",
                str(self.session_dir / "generated_templates") + os.sep,
            ),
        ]
        for active_patch in self._patches:
            active_patch.start()

        import importlib
        import tools.FoG_tools._shared as shared_module
        import tools.FoG_tools.program_template as program_template_module

        importlib.reload(shared_module)
        importlib.reload(program_template_module)
        self.shared = shared_module
        self.pt = program_template_module

        self.shared.PROGRAM_TEMPLATES_FILE = self.templates_file
        self.shared.PROGRAM_WEIGHTS_FILE = self.weights_file
        self.shared.FOG_SESSION_ID = self.session_id
        self.shared.SESSION_DIR = self.session_dir
        self.shared.TEMPLATE_BACKUP_DIR = self.session_dir / "template_backups"
        self.shared.SESSION_METADATA_FILE = self.session_dir / "metadata.json"
        self.shared.GENERATED_TEMPLATE_DIR = str(self.session_dir / "generated_templates") + os.sep

        self.pt.PROGRAM_TEMPLATES_FILE = self.templates_file
        self.pt.PROGRAM_WEIGHTS_FILE = self.weights_file
        self.pt.FOG_SESSION_ID = self.session_id
        self.pt.TEMPLATE_BACKUP_DIR = self.session_dir / "template_backups"
        self.pt.GENERATED_TEMPLATE_DIR = str(self.session_dir / "generated_templates") + os.sep

    def tearDown(self):
        for active_patch in self._patches:
            active_patch.stop()
        shutil.rmtree(str(self.tmp), ignore_errors=True)

    def test_list_program_templates(self):
        result = self.pt._list_program_templates_executor({})
        self.assertIn("Codegen100", result)
        self.assertIn("JIT1Function", result)

    def test_edit_program_templates_file_updates_template_body(self):
        diff = """@@ ProgramTemplate("Codegen100") { b in
     ProgramTemplate("Codegen100") { b in
-        b.buildPrefix()
-        b.build(n: 100)
+        b.build(n: 999)
     },
"""
        result = self.pt._edit_program_template_file_executor(
            {
                "path": "Sources/Fuzzilli/CodeGen/ProgramTemplates.swift",
                "op": "update",
                "diff": diff,
            }
        )

        self.assertIn("OK: Updated", result)
        content = self.templates_file.read_text()
        self.assertIn("b.build(n: 999)", content)
        self.assertNotIn("b.buildPrefix()", content)

    def test_edit_program_templates_file_accepts_wrapped_patch_format(self):
        diff = """*** Begin Patch
*** Update File: Sources/Fuzzilli/CodeGen/ProgramTemplates.swift
@@ ProgramTemplate("JIT1Function") { b in
     ProgramTemplate("JIT1Function") { b in
-        b.buildRepeatLoop(n: 100)
+        b.buildRepeatLoop(n: 250)
     },
*** End Patch
"""
        result = self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplates.swift", "op": "update", "diff": diff}
        )

        self.assertIn("OK: Updated", result)
        self.assertIn("b.buildRepeatLoop(n: 250)", self.templates_file.read_text())

    def test_edit_program_template_weights_file_updates_weight_entry(self):
        diff = """@@ "Codegen100": 2,
 \t"Codegen100": 2,
-\t"JIT1Function": 2,
+\t"JIT1Function": 9,
 ]
"""
        result = self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplateWeights.swift", "op": "update", "diff": diff}
        )

        self.assertIn("OK: Updated", result)
        self.assertIn('"JIT1Function": 9', self.weights_file.read_text())

    def test_edit_program_template_file_rejects_invalid_path(self):
        result = self.pt._edit_program_template_file_executor(
            {"path": "Sources/Fuzzilli/CodeGen/Other.swift", "op": "update", "diff": "@@\n-a\n+b\n"}
        )
        self.assertIn("Error", result)
        self.assertIn("path must target", result)

    def test_edit_program_template_file_reports_multiple_matches(self):
        diff = """@@
     },
+    // duplicate-trigger
"""
        result = self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplates.swift", "op": "update", "diff": diff}
        )
        self.assertIn("Error", result)
        self.assertIn("Found multiple matches", result)

    def test_edit_program_template_file_reports_missing_match(self):
        diff = """@@ missing-anchor
-    this line does not exist
+    replacement
"""
        result = self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplates.swift", "op": "update", "diff": diff}
        )
        self.assertIn("Error", result)
        self.assertIn("No match found", result)

    def test_edit_program_template_file_creates_snapshot(self):
        diff = """@@ ProgramTemplate("Codegen100") { b in
     ProgramTemplate("Codegen100") { b in
-        b.build(n: 100)
+        b.build(n: 101)
     },
"""
        self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplates.swift", "op": "update", "diff": diff}
        )
        backups = list((self.session_dir / "template_backups").glob("pre_edit_*.swift"))
        self.assertTrue(backups)

    def test_edit_program_template_file_rejects_invalid_op(self):
        result = self.pt._edit_program_template_file_executor(
            {"path": "ProgramTemplates.swift", "op": "replace", "diff": "@@\n-a\n+b\n"}
        )
        self.assertIn("Error", result)
        self.assertIn("Unsupported op", result)

    def test_compile_creates_session_scoped_js(self):
        fake_js = "// compiled output\nconsole.log('hi');\n"
        mock_result = type("R", (), {"stdout": fake_js, "stderr": "", "returncode": 0})()

        with patch.object(self.pt, "run_command", return_value=mock_result):
            result = self.pt._compile_program_template_executor({"template": "Codegen100"})

        self.assertIn("Generated JavaScript", result)
        generated_dir = self.session_dir / "generated_templates"
        js_files = list(generated_dir.glob("Codegen100_*.js"))
        self.assertTrue(js_files)
        self.assertIn(self.session_id, js_files[0].name)

    def test_compile_attempt_counter_increments(self):
        fake_js = "// js\n"
        mock_result = type("R", (), {"stdout": fake_js, "stderr": "", "returncode": 0})()

        with patch.object(self.pt, "run_command", return_value=mock_result):
            self.pt._compile_program_template_executor({"template": "JIT1Function"})
            self.pt._compile_program_template_executor({"template": "JIT1Function"})

        generated_dir = self.session_dir / "generated_templates"
        js_files = sorted(generated_dir.glob("JIT1Function_*.js"))
        self.assertEqual(len(js_files), 2)
        self.assertIn("001", js_files[0].name)
        self.assertIn("002", js_files[1].name)

    def test_compile_missing_template_param(self):
        result = self.pt._compile_program_template_executor({})
        self.assertIn("Error", result)

    def test_compile_returns_error_for_nonzero_exit_even_with_stdout(self):
        mock_result = type(
            "R",
            (),
            {
                "stdout": "partial output that is not runnable js\n",
                "stderr": "Fatal error: Unexpectedly found nil while unwrapping an Optional value",
                "returncode": 132,
            },
        )()

        with patch.object(self.pt, "run_command", return_value=mock_result):
            result = self.pt._compile_program_template_executor({"template": "Codegen100"})

        self.assertIn("Swift build failed", result)
        self.assertIn("Fatal error", result)
        generated_dir = self.session_dir / "generated_templates"
        self.assertFalse(list(generated_dir.glob("Codegen100_*.js")))

    def test_compile_returns_error_when_no_javascript_is_emitted(self):
        mock_result = type(
            "R",
            (),
            {
                "stdout": "",
                "stderr": "",
                "returncode": 0,
            },
        )()

        with patch.object(self.pt, "run_command", return_value=mock_result):
            result = self.pt._compile_program_template_executor({"template": "Codegen100"})

        self.assertIn("Swift build failed", result)
        self.assertIn("without emitting JavaScript", result)

    def test_init_session_creates_dirs_and_metadata(self):
        self.shared.SESSION_DIR = self.session_dir
        self.shared.TEMPLATE_BACKUP_DIR = self.session_dir / "template_backups"
        self.shared.SESSION_METADATA_FILE = self.session_dir / "metadata.json"
        self.shared.GENERATED_TEMPLATE_DIR = str(self.session_dir / "generated_templates") + os.sep
        self.shared.PROGRAM_TEMPLATES_FILE = self.templates_file
        self.shared.PROGRAM_WEIGHTS_FILE = self.weights_file
        self.shared.OUTPUT_DIRECTORY = str(self.tmp / "fog-d8-records")

        self.shared._init_session()

        self.assertTrue(self.session_dir.exists())
        self.assertTrue((self.session_dir / "template_backups").exists())
        self.assertTrue((self.session_dir / "generated_templates").exists())
        self.assertTrue((self.session_dir / "metadata.json").exists())
        self.assertTrue((self.session_dir / "template_backups" / "original.swift").exists())
        self.assertTrue((self.session_dir / "template_backups" / "original_weights.swift").exists())

        metadata = json.loads((self.session_dir / "metadata.json").read_text())
        self.assertEqual(metadata["session_id"], self.session_id)
        self.assertIn("started_at", metadata)
        self.assertIn("template_attempts", metadata)

    def test_init_session_idempotent(self):
        self.shared.SESSION_DIR = self.session_dir
        self.shared.TEMPLATE_BACKUP_DIR = self.session_dir / "template_backups"
        self.shared.SESSION_METADATA_FILE = self.session_dir / "metadata.json"
        self.shared.GENERATED_TEMPLATE_DIR = str(self.session_dir / "generated_templates") + os.sep
        self.shared.PROGRAM_TEMPLATES_FILE = self.templates_file
        self.shared.PROGRAM_WEIGHTS_FILE = self.weights_file
        self.shared.OUTPUT_DIRECTORY = str(self.tmp / "fog-d8-records")

        self.shared._init_session()
        first_metadata = (self.session_dir / "metadata.json").read_text()

        (self.session_dir / "template_backups" / "original.swift").write_text("// tampered")
        self.shared._init_session()
        self.assertEqual(
            (self.session_dir / "template_backups" / "original.swift").read_text(),
            "// tampered",
        )
        self.assertEqual((self.session_dir / "metadata.json").read_text(), first_metadata)

    def test_next_attempt_increments(self):
        metadata_file = self.session_dir / "metadata.json"
        self.session_dir.mkdir(parents=True, exist_ok=True)
        metadata_file.write_text(json.dumps({"template_attempts": {}}))

        self.shared.SESSION_METADATA_FILE = metadata_file

        first = self.shared._next_attempt("MyTpl")
        second = self.shared._next_attempt("MyTpl")
        third = self.shared._next_attempt("OtherTpl")

        self.assertEqual(first, 1)
        self.assertEqual(second, 2)
        self.assertEqual(third, 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
