name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 25-nightly

      # Is it failing to run tests b/c we're overriding
      # what swift binary to use?
      - name: Setup Swift for Ubuntu
        if: runner.os == 'Linux'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.3"

      - uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
